version: "3"
services:
  syslog:
    image: jumanjiman/rsyslog
    expose:
      - 514
      - 514/udp
    ports:
      - 514:514
      - 514:514/udp
    volumes:
      - syslog:/var/run/rsyslog/dev
    networks:
      - cc-net
  api:
    build:
      context: .
      args:
        - EXPOSED_PORT=${EXPOSED_PORT_SERVICE}
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - ${EXPOSED_PORT_CONTAINER}:${EXPOSED_PORT_SERVICE}
    networks:
      - cc-net
    links:
      - syslog
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    depends_on:
      - syslog
networks:
  cc-net:
volumes:
  syslog:
