version: "3"
services:
  syslog:
    image: outstand/syslog-ng-stdout:latest
  api:
    build:
      context: .
      args:
        - EXPOSED_PORT=${EXPOSED_PORT_SERVICE}
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment: 
      - EXPOSED_PORT=${EXPOSED_PORT_SERVICE}
    ports:
      - "${EXPOSED_PORT_CONTAINER}:${EXPOSED_PORT_SERVICE}"
    networks: 
      - cc-net
    links:
      - syslog
networks: 
  cc-net:
